services:
  db:
    container_name: pixshare-postgres-db
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: pixshare_db
      PGDATA: /data/postgres
    secrets:
      - postgres-user
      - postgres-password
    volumes:
      - db_data:/data/postgres
    ports:
      - ${POSTGRES_DB_PORT}:5432
    networks:
      - db_net
    restart: unless-stopped

networks:
  db_net:
    driver: bridge

secrets:
  postgres-user:
    environment: POSTGRES_USER
  postgres-password:
    environment: POSTGRES_PASSWORD

volumes:
  db_data: