server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST}:${TEST_DB_PORT}/pixshare_test_db
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'validate'
    show-sql: true

cloudinary:
  upload-folder: ${TEST_CLOUDINARY_UPLOAD_FOLDER}

app:
  # Admin user configuration for testing
  admin:
    email: ${APP_TEST_ADMIN_EMAIL:admin-test@localhost.test}
    password: ${APP_TEST_ADMIN_PASSWORD:$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG} # Default: "password"