name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      postgres:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_TEST_PASSWORD }}
          POSTGRES_DB: pixshare_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${{ vars.TEST_DB_PORT }}:5432
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Send Slack notification about commit message and sha
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": ":github-logo: pix-share-social-app-fullstack-react-springboot repository commit message: ${{ github.event.head_commit.message }} | sha: ${{ github.sha }}",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Send Slack notification about deployment start
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": "Backend deployment started :spring-boot: :radical_rocket: :fingers_crossed: - :github-actions: Job #${{ github.run_id }}",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%Y%m%d.%j.%H%M%S')" >> $GITHUB_OUTPUT

      - name: Send Slack notification about maven build start
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": ":apache_maven: :container: Building with Maven and Jib Maven Plugin",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Build, Package and Push Docker image with Maven
        env:
          ACTIVE_SPRING_PROFILES: test
          TEST_DB_USER: ${{ vars.POSTGRES_TEST_USER }}
          TEST_DB_PASSWORD: ${{ vars.POSTGRES_TEST_PASSWORD }}
          TEST_DB_HOST: ${{ vars.TEST_DB_HOST }}
          TEST_DB_PORT: ${{ vars.TEST_DB_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_TOKEN_ISSUER: ${{ secrets.JWT_TOKEN_ISSUER }}
          JWT_TOKEN_EXPIRY_SECONDS: ${{ secrets.JWT_TOKEN_EXPIRY_SECONDS }}
          APP_BASE_URL: ${{ vars.TEST_APP_BASE_URL }}
          PASSWORD_RESET_TOKEN_SECRET_KEY: ${{ secrets.TEST_PASSWORD_RESET_TOKEN_SECRET_KEY }}
          PASSWORD_RESET_TOKEN_EXPIRY_SECONDS: ${{ vars.TEST_PASSWORD_RESET_TOKEN_EXPIRY_SECONDS }}
          PASSWORD_RESET_ATTEMPT_WINDOW_MAX_ATTEMPTS: ${{ secrets.TEST_PASSWORD_RESET_ATTEMPT_WINDOW_MAX_ATTEMPTS }}
          PASSWORD_RESET_ATTEMPT_WINDOW_DURATION_SECONDS: ${{ vars.TEST_PASSWORD_RESET_ATTEMPT_WINDOW_DURATION_SECONDS }}
          CLOUDINARY_URL: ${{ vars.TEST_CLOUDINARY_URL }}
          CLOUDINARY_UPLOAD_PRESET: ${{ vars.TEST_CLOUDINARY_UPLOAD_PRESET }}
          CLOUDINARY_UPLOAD_FOLDER: ${{ vars.TEST_CLOUDINARY_UPLOAD_FOLDER }}
          BREVO_API_KEY: ${{ secrets.TEST_BREVO_API_KEY }}
        run:
          mvn -B -ntp verify -Ddocker.image.tag=${{ steps.build-number.outputs.BUILD_NUMBER }}

      - name: Send Slack notification about maven build end
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": ":apache_maven: Maven build completed. :docker: Image tag: ${{ steps.build-number.outputs.BUILD_NUMBER }} pushed to Docker Hub: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/pixshare-api",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"  

      - name: Update api image tag in Dockerrun.aws.json with new build number
        run: |
          echo "Dockerrun.aws.json before image tag update:"
          cat ../Dockerrun.aws.json
          sed -i -E 's/(${{ secrets.DOCKERHUB_USERNAME }}\/pixshare-api:)([^"]*)/\1'"${{ steps.build-number.outputs.BUILD_NUMBER }}"'/' ../Dockerrun.aws.json
          echo "Dockerrun.aws.json after image tag update:"
          cat ../Dockerrun.aws.json

      - name: Send Slack notification about elastic beanstalk deployment start
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": ":aws: Deployment to :aws_eb: Elastic Beanstalk started",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.sha }}
          region: ${{ secrets.AWS_EB_REGION }}
          deployment_package: Dockerrun.aws.json

      - name: Send Slack notification about repo commit start
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": ":merge: Committing to :github-logo: pix-share-social-app-fullstack-react-springboot repository",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Fetch changes from remote main branch
        run: |
          git fetch origin main
          git branch
          git branch -r

      - name: Switch to target branch
        run: |
          git checkout ${{ vars.TARGET_BRANCH }}
          git pull

      - name: Merge main branch into target branch
        run: |
          echo "Branch ref: ${{ github.ref }}"
          echo "Target branch: ${{ vars.TARGET_BRANCH }}"
          git branch
          git branch -r
          git merge origin/main

      - name: Commit changes in Dockerrun.aws.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update Dockerrun.aws.json with new api image tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ vars.TARGET_BRANCH }}
          force: false  # Avoid force pushing

      - name: Send Slack notification about elastic beanstalk deployment and repo commit end
        run: >
          curl -X POST -H 'Content-type: application/json' --data '
          {
            "text": "Deployment and commit completed :completed: :partytime: - ${{ secrets.AWS_EB_ENVIRONMENT_URL  }}",
          }
          ' "${{ secrets.SLACK_WEBHOOK_URL }}"

      - name: Send Slack notification about job end
        if: always()
        run: |
          STATUS_MESSAGE=":question: Unknown"
          if [ "${{ job.status }}" = "success" ]; then
                STATUS_MESSAGE=":github-check-mark: Success"
          elif [ "${{ job.status }}" = "failure" ]; then
                STATUS_MESSAGE=":github-changes-requested: Failed"            
          elif [ "${{ job.status }}" = "cancelled" ]; then
                STATUS_MESSAGE=":gitlab-warning: Cancelled"
          fi
          
          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"Job Status: ${STATUS_MESSAGE}\" }" "${{ secrets.SLACK_WEBHOOK_URL }}"